spring:
  application:
    name: oxtest
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 60000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/oxtest

server:
  port: 8081

keycloak:
  auth-server-url: http://localhost:8080
  realm: oxtest
  resource: admin-cli
  credentials:
    secret: qyMbm8wqHPDe1njNUwWR3ddpLf02y2O6

